-- Explore all Countries our Customers come from
select
	distinct country
from gold_dim_customers

-- Explore all categories "The Major Divisions"
select
	distinct category,
	subcategory ,
	product_name 
from gold_dim_products
order by 1, 2, 3 

-- find the date of the first and last order
-- how many year of sales are avaible

select 
	min(order_date) as first_date,
	max(order_date) as last_date,
	--date_part('month', age(max(order_date),min(order_date)))* 12  as year_date
	(date_part('year', age(max(order_date), min(order_date))) * 12) + 
	   date_part('month', age(max(order_date), min(order_date))) as order_range_month
from gold_fact_sales gfs 


-- find the youngest and oldest customer

select 
	min(gdc.birthdate) as youngest,
	max(gdc.birthdate) as oldest,
	date_part('year', age(current_date, min(gdc.birthdate))),
	date_part('year', age(current_date, max(gdc.birthdate)))
from gold_dim_customers gdc 


-- Find the total sales

select 
	sum(gfs.sales_amount ) as total_sales
from gold_fact_sales gfs 

-- find how many items are sold
select 
	sum(gfs.quantity ) as total_sold
from gold_fact_sales gfs 

-- Find the average selling price
select 
	round( avg(gfs.price ),2) as avg_price
from gold_fact_sales gfs 


-- find the total number of Order
select 
	count(order_number) as total_order
from gold_fact_sales gfs 

select 
	count(distinct order_number) as total_order
from gold_fact_sales gfs 

-- find the total number of products
select
	count(product_name) as total_products
from gold_dim_products

select
	count(distinct product_name) as total_products
from gold_dim_products

-- find the total number of customers
select
	COUNT(customer_key) as total_customers
from gold_dim_customers;


-- find the total number of customers that has pllaced an order
select
	COUNT(distinct customer_key) as total_customers
from gold_fact_sales

-- Gerate a Report that shows all key metrics of the business

select 
	'Total sales' as measure_name,
	sum(gfs.sales_amount ) as measure_value
from gold_fact_sales gfs 
union all
select 
	'Total Quantity',
	sum(gfs.quantity  ) as measure_value
from gold_fact_sales gfs
union all 
select 
	'average price',
	round( avg(gfs.price ),2) as avg_price
from gold_fact_sales gfs 
union all
select 'total number order',
	count(distinct order_number) as total_order
from gold_fact_sales gfs 
union all
select
	'total number product',
	count(distinct product_name) as total_products
from gold_dim_products
union all
select 
	'total number customer',
	COUNT(customer_key) as total_customers
from gold_dim_customers

-- =====================

-- find total customers by countries

select 
	country,
	count(customer_key) as total_customers
from gold_dim_customers gdc 
group by 1
order by 2 desc

-- find total customers by gender

select 
	gender ,
	count(customer_key ) as total_customers
from gold_dim_customers
group by gender

-- find total products by category

select 
	gdp.category ,
	count(gdp.product_name ) as total_procuts_name
from gold_dim_products gdp 
group by 1
order by 2 desc 

-- what is the average costs in each category?

select 
	category,
	round(avg(gdp."cost"),3)
from gold_dim_products gdp 
group by category 
order by 2 desc

-- what is the total revenue generated by each category?

select 
	gdp.category ,
	sum(gfs.sales_amount ) total_revenue
from gold_fact_sales gfs
left join gold_dim_products gdp 
	on gdp.product_key = gfs.product_key
group by category

-- find total revenue is generated by customer

select
	gdc.customer_key ,
	gdc.first_name,
	gdc.last_name ,
	sum(sales_amount) as total_revenue
from gold_fact_sales gfs 
left join gold_dim_customers gdc 
	on gdc.customer_key = gfs.customer_key
group by 1,2,3
order by 4 desc 
limit 15
-- what is the distribution of sold items across countries?

select
	gdc.country ,
	sum(gfs.quantity ) as total_sold_item
from gold_fact_sales gfs 
left join gold_dim_customers gdc 
	on gdc.customer_key = gfs.customer_key
group by country
order by total_sold_item desc 

-- which 5 products generate the highest revenue

select
	gdp.product_name ,
	sum(gfs.sales_amount ) total_revenue,
	row_number() over(order by sum(gfs.sales_amount) desc) as rank_products
from gold_fact_sales gfs
left join gold_dim_products gdp 
	on gdp.product_key = gfs.product_key
group by gdp.product_name 
limit 5



-- what are the 5 worts-preforming products in term of sales

select
	gdp.product_name ,
	sum(gfs.sales_amount ) total_revenue
from gold_fact_sales gfs
left join gold_dim_products gdp 
	on gdp.product_key = gfs.product_key
group by gdp.product_name 
order by total_revenue asc
limit 5


